name: Deploy Backend to Fly.io

on:
  push:
    branches:
      - main
    paths:
      - 'api/**'
      - '.github/workflows/deploy-backend.yml'

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: './api/package-lock.json'

      - name: Install dependencies
        run: npm ci
        working-directory: ./api

      - name: Run Database Migrations
        run: npm run db:migrate
        working-directory: ./api
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          DATABASE_AUTH_TOKEN: ${{ secrets.DATABASE_AUTH_TOKEN }}

      - uses: superfly/flyctl-actions/setup-flyctl@master
      
      - run: flyctl deploy --remote-only
        working-directory: ./api
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
