name: Deploy Frontend to Vercel
on:
  push:
    branches:
      - main
    paths:
      - 'web/**'
      - '.github/workflows/deploy-frontend.yml'

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Install dependencies
        run: npm install
      - name: Deploy Project to Vercel
        run: vercel deploy --prod --yes --token=${{ secrets.VERCEL_TOKEN }} --env VITE_API_BASE_URL=https://bright-abodes.fly.dev
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
